package dao;

import dao.jdbc.JdbcOwnerDao;
import domain.Owner;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

public class JdbcOwnerDaoTest {

    private static final String URL = "jdbc:mysql://localhost:3306/catnowner_test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true";
    private static final String USER = "root";
    private static final String PASS = "";

    private JdbcOwnerDao _dao;

    @BeforeEach
    void setUp() throws Exception {
        _dao = new JdbcOwnerDao(URL, USER, PASS);
        try (Connection c = DriverManager.getConnection(URL, USER, PASS)) {
            c.createStatement().executeUpdate("DELETE FROM cats");
            c.createStatement().executeUpdate("DELETE FROM owners");
        }
        _dao.insert(new Owner("John", "Doe", 30, "123 Main St", "0871234567", "john@example.com"));
    }

    @Test
    void findOwnerById_returnsEmptyOptional_whenIdDoesNotExist() throws Exception {
        Optional<Owner> result = _dao.findOwnerById(99999);
        assertFalse(result.isPresent());
    }

    @Test
    void insert_returnsOwnerWithAutoGeneratedId_whenOwnerIsValid() throws Exception {
        Owner inserted = _dao.insert(new Owner("Alice", "Smith", 28, "789 Oak Ave", "0871234569", "alice@example.com"));
        assertTrue(inserted.getId() > 0);
    }

    @Test
    void findAllOwners_returnsInsertedOwners() throws Exception {
        List<Owner> owners = _dao.findAllOwners();
        assertFalse(owners.isEmpty());
    }

    @Test
    void deleteById_returnsTrue_whenOwnerExists() throws Exception {
        Owner inserted = _dao.insert(new Owner("Tom", "Brown", 40, "1 St", "0871234571", "tom@example.com"));
        assertTrue(_dao.deleteById(inserted.getId()));
    }

    @Test
    void deleteById_returnsFalse_whenIdDoesNotExist() throws Exception {
        assertFalse(_dao.deleteById(99999));
    }

    @Test
    void updateOwner_updatesFieldsCorrectly() throws Exception {
        Owner inserted = _dao.insert(new Owner("Tom", "Brown", 40, "1 St", "0871234571", "tom@example.com"));
        Owner updated  = _dao.updateOwner(inserted.getId(), new Owner("Tommy", "Brown", 41, "2 St", "0871234571", "tommy@example.com"));
        assertEquals("Tommy", updated.getFirstName());
    }

    @Test
    void uploadImage_andRetrieve_bytesMatch() throws Exception {
        Owner inserted  = _dao.insert(new Owner("Alice", "Smith", 28, "2 St", "0871234569", "alice@example.com"));
        byte[] imgBytes = { 10, 20, 30, 40, 50 };
        _dao.uploadImage(inserted.getId(), imgBytes, "photo.png", "image/png", imgBytes.length);
        Owner retrieved = _dao.getOwnerImage(inserted.getId());
        assertArrayEquals(imgBytes, retrieved.getOwnerImage());
    }

    @Test
    void getOwnerMetadata_doesNotReturnBlob() throws Exception {
        Owner inserted  = _dao.insert(new Owner("Alice", "Smith", 28, "2 St", "0871234569", "alice@example.com"));
        byte[] imgBytes = { 10, 20, 30 };
        _dao.uploadImage(inserted.getId(), imgBytes, "photo.png", "image/png", imgBytes.length);
        Owner meta = _dao.getOwnerMetadata(inserted.getId());
        assertNull(meta.getOwnerImage());
        assertEquals("photo.png", meta.getFileName());
    }

    @Test
    void findOwnersByFilter_returnsMatchingOwners() throws Exception {
        _dao.insert(new Owner("Alice", "Smith", 28, "2 St", "0871234569", "alice@example.com"));
        List<Owner> result = _dao.findOwnersByFilter(o -> o.getFirstName().equals("Alice"));
        assertEquals(1, result.size());
    }
}
