package dao;

import dao.jdbc.JdbcCatDao;
import domain.Cat;
import domain.Gender;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Date;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

/** Unit tests for {@link JdbcCatDao}.
 * @author Bernard Joyce
 */
public class JdbcCatDaoTest {

    private static final String URL = "jdbc:mysql://localhost:8889/catnowner_test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true";
    private static final String USER = "root";
    private static final String PASS = "root";

    private JdbcCatDao _dao;

    @BeforeEach
    void setUp() throws Exception {
        _dao = new JdbcCatDao(URL, USER, PASS);

        try (Connection c = DriverManager.getConnection(URL, USER, PASS)) {
            c.createStatement().executeUpdate("DELETE FROM nutrition");
            c.createStatement().executeUpdate("DELETE FROM cats");
            c.createStatement().executeUpdate("DELETE FROM owners");

            c.createStatement().executeUpdate(
                    "INSERT INTO owners (ID, FirstName, LastName, Age, Address, Phone, Email) " +
                            "VALUES (1, 'Test', 'Owner', 25, '123 Lane', '085', 'test@test.com')"
            );
        }
    }

    @Test
    @DisplayName("findById returns empty Optional when ID does not exist")
    void findCatById_returnsEmptyOptional_whenIdDoesNotExist() throws Exception {
        Optional<Cat> result = _dao.findById(99999);
        assertFalse(result.isPresent(), "Expected Optional to be empty for non-existent ID");
    }

    @Test
    @DisplayName("insert returns valid auto-generated ID and persists data")
    void insert_returnsValidAutoGeneratedId_whenCatIsValid() throws Exception {
        Cat milo = new Cat.Builder()
                .ownerId(1)
                .name("Milo")
                .gender(Gender.MALE)
                .breed("Tabby")
                .dateOfBirth(Date.valueOf("2024-01-01"))
                .colour("Orange")
                .identifyingMarkings("White paws")
                .fileName("milo.jpg")
                .contentType("image/jpeg")
                .fileSize(1024)
                .catImage(new byte[]{0})
                .build();
        int generatedId = _dao.insert(milo);

        assertTrue(generatedId > 0, "The returned ID should be greater than 0");

        Optional<Cat> retrieved = _dao.findById(generatedId);
        assertTrue(retrieved.isPresent(), "Cat should be retrievable after insert");
        assertEquals("Milo", retrieved.get().getName());
    }

    @Test
    @DisplayName("JSON Round-trip maintains data integrity including binary image data")
    void serialiseDeserialiseMaintainsDataIntegrityForBinaryData() throws Exception {
        byte[] fakeImage = {1, 2, 3, 4, 5};
        Cat original = new Cat.Builder()
                .id(50)
                .ownerId(1)
                .name("Pixel")
                .gender(Gender.FEMALE)
                .breed("Digital")
                .dateOfBirth(Date.valueOf("2020-05-05"))
                .colour("Black")
                .identifyingMarkings("None")
                .catImage(fakeImage)
                .fileName("pixel.png")
                .build();

        String json = _dao.serialise(original);
        Cat result = _dao.deSerialise(json);

        assertNotNull(result, "Deserialized cat should not be null");
        assertEquals(original.getName(), result.getName());

        assertArrayEquals(original.getCatImage(), result.getCatImage(),
                "Image bytes must match after JSON serialization/deserialization");
    }
}